#!/usr/bin/env bash
# Script that transfers file to server
if [ $# -lt 4 ]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_kEY"
   exit 1
fi
#assigning paramentals of variabes

path_to_file=$1
ip=$2
username=$3
path_to_shh_key=$4

#disabbling strict host key checking

scp -0 "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

#checking if the transfer was successful 
if [ $? -eq 0]
then
	echo "FILE WAS TRANSFERD SUCCESSFULLY"
else
	echo "FILE TRASNSFER FAILED"
fi
